# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shubham-reports"
client_id = "b59bd07eca89b42995de6af80ed18ee8"
application_url = "https://trials-scale-refinance-resulting.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shubhamneema123.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_all_orders,read_orders,write_orders,read_customers,write_customers,read_inventory,write_inventory"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://trials-scale-refinance-resulting.trycloudflare.com/auth/callback",
  "https://trials-scale-refinance-resulting.trycloudflare.com/auth/shopify/callback",
  "https://trials-scale-refinance-resulting.trycloudflare.com/api/auth/callback",
  "https://trials-scale-refinance-resulting.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
